graph TD
    A["User Accessible Computers:"] --> B["User Sessions"]
    
    B --> C["Onboarding Mode<br>(Windows Single-App kiosk)"]
    B --> D["Operating Mode<br>(Windows Assigned App Session)"]
    B --> E["Staff Management Mode<br>(Standard Windows)"]
    
    C --> F["Description:<br>We have a limited session (a web<br>browser) that allows students to<br>onboard and complete training<br>sessions."]
    D --> G["Description:<br>This is the general use session, it<br>gives students access to the<br>Applications we specify and<br>prohibits them misusing or<br>damaging the computer."]
    E --> H["Description:<br>Used by Staff Members to<br>administrate, update, and<br>troubleshoot the Operating and<br>Onboarding Modes."]